# Generated by Django 6.0.2 on 2026-03-02 11:36

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='ML Fest Round 2 - ML Debugging Challenge', max_length=200)),
                ('is_active', models.BooleanField(default=False)),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('max_tab_switches', models.PositiveIntegerField(default=3)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('leaderboard_public', models.BooleanField(default=True)),
                ('show_score_to_participant', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'r2_event',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'r2_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('challenge_type', models.CharField(choices=[('classification', 'Classification'), ('regression', 'Regression')], max_length=20)),
                ('notebook_filename', models.CharField(help_text='Filename in Yugam_ML_Challenge-2/ folder', max_length=200)),
                ('total_bugs', models.PositiveIntegerField(default=0)),
                ('order', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='debugchallenge.event')),
            ],
            options={
                'db_table': 'r2_challenge',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, default='', max_length=15)),
                ('role', models.CharField(choices=[('participant', 'Participant'), ('evaluator', 'Evaluator')], default='participant', max_length=15)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('disqualified', 'Disqualified')], default='pending', max_length=15)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('tab_switch_count', models.PositiveIntegerField(default=0)),
                ('tab_switch_violated', models.BooleanField(default=False)),
                ('score', models.IntegerField(default=0)),
                ('time_taken_ms', models.BigIntegerField(default=0)),
                ('has_submitted', models.BooleanField(default=False)),
                ('evaluator', models.ForeignKey(blank=True, limit_choices_to={'role': 'evaluator'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_participants', to='debugchallenge.participant')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='debugchallenge.event')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='r2_participant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'r2_participant',
                'ordering': ['-score', 'time_taken_ms'],
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_type', models.CharField(choices=[('classification', 'Classification'), ('regression', 'Regression')], max_length=20)),
                ('bug_results', models.JSONField(default=dict, help_text='Dict of bug_number(str): is_correct(bool)')),
                ('score', models.IntegerField(default=0)),
                ('evaluated_at', models.DateTimeField(auto_now=True)),
                ('evaluator', models.ForeignKey(limit_choices_to={'role': 'evaluator'}, on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_given', to='debugchallenge.participant')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_received', to='debugchallenge.participant')),
            ],
            options={
                'db_table': 'r2_evaluation',
                'ordering': ['participant', 'challenge_type'],
                'unique_together': {('evaluator', 'participant', 'challenge_type')},
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(upload_to='submissions/%Y/%m/%d/')),
                ('submitted_at', models.DateTimeField(auto_now=True)),
                ('score', models.IntegerField(default=0)),
                ('is_graded', models.BooleanField(default=False)),
                ('admin_notes', models.TextField(blank=True, default='')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='debugchallenge.challenge')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='debugchallenge.participant')),
            ],
            options={
                'db_table': 'r2_submission',
                'ordering': ['-submitted_at'],
                'unique_together': {('participant', 'challenge')},
            },
        ),
    ]
